# Generated by Django 5.2.7 on 2025-10-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ownersinfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=13)),
                ("division", models.CharField(max_length=50)),
                ("district", models.CharField(max_length=50)),
                ("upazila", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=120)),
            ],
        ),
    ]
