# Generated by Django 5.2.7 on 2025-10-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patientinfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=13)),
                ("appication_time", models.DateTimeField(auto_now=True)),
                ("tag", models.CharField(max_length=30)),
                ("species", models.CharField(max_length=60)),
                ("breed", models.CharField(max_length=50)),
                ("weight", models.DecimalField(decimal_places=2, max_digits=6)),
                ("age", models.DecimalField(decimal_places=2, max_digits=5)),
                ("sex", models.CharField(max_length=10)),
                ("pregnancy", models.BooleanField()),
                (
                    "pregnancy_month",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("parity", models.CharField()),
                ("milk_yield", models.DecimalField(decimal_places=2, max_digits=5)),
                ("date_of_parturition", models.DateField()),
                ("date_of_oestrus", models.DateField()),
                ("total_animals", models.IntegerField()),
                ("total_sick_animals", models.IntegerField()),
                ("total_dead_animals", models.IntegerField()),
                ("duration_of_illness", models.IntegerField()),
                ("complaint", models.TextField()),
                ("disease_history", models.TextField()),
                ("treatment_history", models.TextField()),
                ("management_history", models.TextField()),
            ],
        ),
    ]
