# Generated by Django 5.2.7 on 2025-10-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0002_patientinfo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientinfo",
            name="age",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=-1, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="patientinfo",
            name="breed",
            field=models.CharField(default="Unknown", max_length=50),
        ),
        migrations.AlterField(
            model_name="patientinfo",
            name="complaint",
            field=models.TextField(default="Unknown"),
        ),
        migrations.AlterField(
            model_name="patientinfo",
            name="date_of_oestrus",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="patientinfo",
            name="date_of_parturition",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="patientinfo",
            name="disease_history",
            field=models.TextField(default="Unknown"),
        ),
        migrations.AlterField(
            model_name="patientinfo",
            name="duration_of_illness",
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name="patientinfo",
            name="management_history",
            field=models.TextField(default="Unknown"),
        ),
        migrations.AlterField(
            model_name="patientinfo",
            name="milk_yield",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=-1, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="patientinfo",
            name="pregnancy",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="patientinfo",
            name="pregnancy_month",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=-1, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="patientinfo",
            name="sex",
            field=models.CharField(default="female", max_length=10),
        ),
        migrations.AlterField(
            model_name="patientinfo",
            name="species",
            field=models.CharField(default="Unknown", max_length=60),
        ),
        migrations.AlterField(
            model_name="patientinfo",
            name="tag",
            field=models.CharField(default="Unknown", max_length=30),
        ),
        migrations.AlterField(
            model_name="patientinfo",
            name="total_animals",
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name="patientinfo",
            name="total_dead_animals",
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name="patientinfo",
            name="total_sick_animals",
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name="patientinfo",
            name="treatment_history",
            field=models.TextField(default="Unknown"),
        ),
        migrations.AlterField(
            model_name="patientinfo",
            name="weight",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=-1, max_digits=6, null=True
            ),
        ),
    ]
