# Generated by Django 5.2.7 on 2025-10-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0003_alter_patientinfo_age_alter_patientinfo_breed_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patientinfo",
            old_name="appication_time",
            new_name="application_time",
        ),
        migrations.AlterField(
            model_name="ownersinfo",
            name="address",
            field=models.CharField(blank=True, default="Unknown", max_length=120),
        ),
        migrations.AlterField(
            model_name="ownersinfo",
            name="district",
            field=models.CharField(blank=True, default="Unknown", max_length=50),
        ),
        migrations.AlterField(
            model_name="ownersinfo",
            name="division",
            field=models.CharField(blank=True, default="Unknown", max_length=50),
        ),
        migrations.AlterField(
            model_name="ownersinfo",
            name="name",
            field=models.CharField(blank=True, default="Unknown", max_length=100),
        ),
        migrations.AlterField(
            model_name="ownersinfo",
            name="phone",
            field=models.CharField(blank=True, default="Unknown", max_length=13),
        ),
        migrations.AlterField(
            model_name="ownersinfo",
            name="upazila",
            field=models.CharField(blank=True, default="Unknown", max_length=50),
        ),
        migrations.AlterField(
            model_name="patientinfo",
            name="complaint",
            field=models.TextField(blank=True, default="Unknown"),
        ),
        migrations.AlterField(
            model_name="patientinfo",
            name="disease_history",
            field=models.TextField(blank=True, default="Unknown"),
        ),
        migrations.AlterField(
            model_name="patientinfo",
            name="management_history",
            field=models.TextField(blank=True, default="Unknown"),
        ),
        migrations.AlterField(
            model_name="patientinfo",
            name="name",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AlterField(
            model_name="patientinfo",
            name="parity",
            field=models.CharField(default="Unknown", max_length=10),
        ),
        migrations.AlterField(
            model_name="patientinfo",
            name="phone",
            field=models.CharField(default="Unknown", max_length=13),
        ),
        migrations.AlterField(
            model_name="patientinfo",
            name="treatment_history",
            field=models.TextField(blank=True, default="Unknown"),
        ),
    ]
