# Generated by Django 5.2.7 on 2025-10-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "user_app",
            "0004_rename_appication_time_patientinfo_application_time_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientinfo",
            name="breed",
            field=models.CharField(default="Unknown", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="patientinfo",
            name="species",
            field=models.CharField(default="Unknown", max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="patientinfo",
            name="tag",
            field=models.CharField(default="Unknown", max_length=30, null=True),
        ),
    ]
