# Generated by Django 5.2.7 on 2025-10-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0005_alter_patientinfo_breed_alter_patientinfo_species_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientinfo",
            name="complaint",
            field=models.TextField(blank=True, default="Unknown", null=True),
        ),
        migrations.AlterField(
            model_name="patientinfo",
            name="disease_history",
            field=models.TextField(blank=True, default="Unknown", null=True),
        ),
        migrations.AlterField(
            model_name="patientinfo",
            name="management_history",
            field=models.TextField(blank=True, default="Unknown", null=True),
        ),
        migrations.AlterField(
            model_name="patientinfo",
            name="treatment_history",
            field=models.TextField(blank=True, default="Unknown", null=True),
        ),
    ]
